# Generated by Django 4.1.7 on 2023-04-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_url',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
