# Generated by Django 4.1.7 on 2023-04-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_item_url_alter_item_cat_alter_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_url',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
