# Generated by Django 4.1.7 on 2023-04-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_item_item_url_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_url',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
