# Generated by Django 4.1.7 on 2023-04-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_item_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_url',
            field=models.URLField(),
        ),
    ]
