# Generated by Django 4.1.7 on 2023-04-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_item_item_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_url',
        ),
    ]
